## Dados Raw, da forma que vieram do site

In [1]:
import pandas as pd

df = pd.read_csv("lncRNA.tsv", sep='\t')
display(df.head())
print(df.shape)

,ncRNA Symbol,ncRNA Category,Species,Disease Name,Sample,Dysfunction Pattern,Validated Method,Description,Clinical Application,Causality,Causal Description,PubMed ID
0,ARHGAP5-AS1,LncRNA,Homo sapiens,"Carcinoma, Hepatocellular",HCC cells and tissues,Epigenetics( m6 A-modified),qRT-PCR,"Among these lncRNAs, we found that ARHGAP5-AS1...",NaN,Yes,ARHGAP5-AS1 remarkably promotes malignant beha...,36354136
1,HOTTIP,LncRNA,Homo sapiens,Osteosarcoma,OS tissues,Interaction(PTBP1/KHSRP ),qRT-PCR//RIP,Our data demonstrated HOTTIP was upregulated i...,NaN,Yes,HOTTIP knockdown resulted in a suppression of ...,33475442
2,HOTTIP,LncRNA,Homo sapiens,Glioma,SF268 cells,Interaction(miRNA-10b/Zeb1/Zeb2),Transfection//Migration Assay//qRT-PCR//MTT//E...,lncRNA HOTTIP was found to be particularly ele...,NaN,Yes,lncRNA HOTTIP was found to be particularly ele...,35402278
3,HOTTIP,LncRNA,Homo sapiens,Retinoblastoma,RB tissues and cells,Interaction(miR-101-3p/STC1 Axis),In Vivo Experiment//RNA Pull-Down//Western Blo...,HOTTIP expression was promoted in RB tissues a...,NaN,Yes,Downregulation of HOTTIP inhibited proliferati...,33784880
4,HOTTIP,LncRNA,Homo sapiens,stomach carcinoma,"cell lines MGC-803, HGC-27, SNU-1, and SGC-7901",regulation[adsorbing miR-615-3p],CCK8//qRT-PCR//Flow Cytometry//Luciferase Repo...,LncRNA HOTTIP was highly expressed in gastric...,NaN,Yes,"After knockdown of lncRNA HOTTIP, the prolife...",32633359

(25440, 12)

In [2]:
print(df.iloc[:, 1].unique()) # tipos de ncRNA
print("\n")
print(df.iloc[:, 2].unique()) # tipos de espécie

<StringArray>
['LncRNA', 'CircRNA', 'miRNA']
Length: 3, dtype: str


<StringArray>
['Homo sapiens', 'Mus musculus', 'Rattus norvegicus', 'Oryctolagus cuniculus']
Length: 4, dtype: str

## Filtrando apenas dados de lncRNA de humanos

In [3]:
df_filtered = df[
    (df.iloc[:, 1] == 'LncRNA') &
    (df.iloc[:, 2] == 'Homo sapiens')
]

print(df_filtered.iloc[:, 1].unique())
print(df_filtered.iloc[:, 2].unique())
print(df_filtered.shape)

<StringArray>
['LncRNA']
Length: 1, dtype: str
<StringArray>
['Homo sapiens']
Length: 1, dtype: str
(12133, 12)

## Removendo colunas desnecessárias

In [5]:
"""
Manter ncRNA Symbol para poder buscar as sequências;
Manter Disease Name para definir os alvos da classficação
"""

columns_to_remove = [
    'ncRNA Category',
    'Species',
    'Sample',
    'Dysfunction Pattern',
    'Validated Method',
    'Description',
    'Clinical Application',
    'Causality',
    'Causal Description',
    'PubMed ID'
]

df_filtered = df_filtered.drop(columns=columns_to_remove)
df_filtered = df_filtered.dropna(subset=['ncRNA Symbol', 'Disease Name'])

display(df_filtered)
print(df_filtered.shape)

      ncRNA Symbol                        Disease Name
0      ARHGAP5-AS1           Carcinoma, Hepatocellular
1           HOTTIP                        Osteosarcoma
2           HOTTIP                              Glioma
3           HOTTIP                      Retinoblastoma
4           HOTTIP                   stomach carcinoma
...            ...                                 ...
25434        CASC8                      Retinoblastoma
25435        CASC8                    Coronary Disease
25436        CASC8                        Tuberculosis
25437        CASC8           Diabetes Mellitus, Type 2
25438       CASC20  Esophageal Squamous Cell Carcinoma

[12133 rows x 2 columns]

(12133, 2)

## Criando as Colunas Alvo

CONTINUAR CONTANDO A FREQUÊNCIA DA COLUNA ALVO; FILTRAR POR FREQUÊNCIA E AGRUPAR (DOENÇAS DO CORAÇÃO, PULMÃO, ETC). FAZER ENCODING PARA CADA GRUPO OCUPAR UMA COLUNA BINÁRIA (0, 1)